### ISSUE TITLE
Final search result is focused in continue reading

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#226] opened 2023-08-09 14:16 UTC
### Type of installation

Portable (.zip)

### Steps to reproduce

1. Search for any present name in continue reading.
2. The final search result record is focused in continue reading.

---

https://github.com/mienaiyami/yomikiru/assets/127277950/c3cb9c56-004d-4cbb-9ff9-05113adc5e91

### ✔️ Expected Behavior

To not focus the final search result.

### ❌ Actual Behavior

Final search result is focused.

**Comment by mienaiyami** [comment] 2023-08-09 14:20
It was originally just a side effect of adding keyboard controls in search. But I kept it as an indicator that click enter in search now will open the item. 
I will remove focus but keep the enter function if it looks annoying.

**Comment by mienaiyami** [comment] 2023-08-09 14:56
It's caused by same thing in #225, So I will be closing that.

**Closed** 2023-08-09 18:32 UTC
Labels: bug
