### ISSUE TITLE
[BUG] App hangs during loading of new chapter/volume

### ISSUE THREAD

**Issue by bidaumm** [mienaiyami/yomikiru#210] opened 2023-07-20 04:50 UTC
I am currently using the app to read volumes of One Piece and as per title the app hangs during loading of new chapter/volume When this happens I can click and see the animations for the clicks on the title bar still, however the body of the window is just a black screen. Clicking the X to close the app doesn't work and the only method to quit is via force killing of the process.

This is not a constant occurrence. In some cases I can load chapters in some cases it'll hang when attempting to load the next one directly after. (Never during loading of first chapter after opening app however)
I have tested with both loading from cbz and also loading directly from the extracted folder from the CBZ and in both cases it is occuring. 

The volumes are around 180-200 pages in length, I haven't read anything that is a chapter length to be able to prove its happening on lower count items as well but if I do and it happens I will update.

Next time this occurs I will update the issue with a screenshot of how the UI looks.
I can provide any logs/dumps/screenshots etc that are required to help diagnose the issue so feel free to request them if it'll help

**Comment by mienaiyami** [comment] 2023-07-20 05:23
> When this happens I can click and see the animations for the clicks on the title bar

From this you mean only the buttons in top right?



> I can provide any logs/dumps/screenshots etc that are required to help diagnose the issue so feel free to request them if it'll help

Also, click `ctrl+shift+i` and send screenshot of any window that opens, if it still working. There might be some unhandled error I didn't account for.

**Comment by bidaumm** [comment] 2023-07-21 20:49
Had a hang happen again - this time it was in fullscreen and couldn't exit full screen, nor open developer tools.
Going to keep the app running with verbose loggin enabled via and will upload log next time I get a hang
`.\yomikiru.exe --enable-logging --v=1`

**Comment by mienaiyami** [comment] 2023-07-21 21:48
Check the generated log file under "Settings->About->Last button" if you notice something.

**Comment by bidaumm** [comment] 2023-07-22 13:35
[main.log](https://github.com/mienaiyami/yomikiru/files/12136578/main.log)
[yomikiru.log](https://github.com/mienaiyami/yomikiru/files/12136579/yomikiru.log)
Just got a hang with logging enabled
The last line in the log window was `Renderer process oom - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.`

I've attached both the main.log and full verbose log above.

**Comment by mienaiyami** [comment] 2023-07-22 15:29
Can't be sure but I think its related to #141. 
If not, then might be related to total ram usage. Can you tell me the resolution or size of an image? As it is a 32bit application it has limited RAM access.
Additionally, main.log is log of backend, and renderer.log is log frontend. This issue is probably on front side.

> In some cases I can load chapters in some cases it'll hang when attempting to load the next one directly after

Can you elaborate further on that?

**Comment by bidaumm** [comment] 2023-07-22 15:59
> Can you elaborate further on that?

I'm using the app to read the One Piece volumes (1-99) currently
I originally had them in the CBZ archives in the location d:\XXXX\OnePiece\XXXX
The app was hanging at this point so I extracted them all out to folders in the same location to test if it was an issue with loading from the temp directory set in here
![image](https://github.com/mienaiyami/yomikiru/assets/30007328/0c78e185-1665-41f8-9b90-b6f13fcc562a)
However it would still hang after that

To give you an idea each volume is around 200~ images large
![image](https://github.com/mienaiyami/yomikiru/assets/30007328/9e77e158-1d3d-4407-9201-1f0ecf34d388)

When loading the app from fresh I can load and read as expected, most of the time I'm also to readall the way through a volume and then loading up the next from the end-page here
![image](https://github.com/mienaiyami/yomikiru/assets/30007328/b9f3c50a-7f90-4fbb-9e0c-4ace9205152c)

The hang itself happens when going over to the next volume at which point the app locks up and instead of showing the usual progress bar it'll hang at the black screen I mentioned previously. This isn't consistent though and sometimes I am able to transfer to the next volume 10+ times in a row.. sometimes it'll hang after just attempting to transfer after the first.

After force quitting the application I'm able to load the volume that it hung on previously and then continue as expected... until the next hang, whenever it decided to happen.

My laymens guess would be that garbage collection processes aren't running properly and clearing cache inbetween volumes causing it to run oom and post the "renderer oom" error, but I don't have enough experience to say anything more than best guesses.

**Comment by mienaiyami** [comment] 2023-07-22 20:03
> My laymens guess would be that garbage collection processes aren't running properly and clearing cache inbetween volumes

Actually, I cant control the garbage collector, I just try to force it to clear cache when chapter changes. It caches all opened images and 

From what I can see the issue is being caused by memory limit of 32bit app (4GB). Maybe I need to build for 64bit.

**Comment by mienaiyami** [comment] 2023-07-24 16:10
64bit version released. I will close this for now, please report if you encounter this issue again.

**Closed by mienaiyami** 2023-07-24 16:10 UTC
Labels: bug
