### ISSUE TITLE
List Item BG Color Hovered

### ISSUE THREAD

**Issue by zeoint** [mienaiyami/yomikiru#234] opened 2023-08-10 07:07 UTC
### Type of installation

Portable (.zip)

### List Item BG Color Hovered is not working for drop down list items, instead they are linked to button foucs color.

1. Open theme maker.
2. Cycle through any drop down list.
3. You can see the hover color.
4. Change ListI tem BG Color Hovered to another color and repeat step 2.
5. You cannot see the chosen color.
6. Change button focus color to another color and repeat step 2.
7. You can see the chosen color on hovering over the items in the drop down list.

---

https://github.com/mienaiyami/yomikiru/assets/127277950/8a063325-f465-402f-99db-8736d4d1f29c

### ✔️ Expected Behavior

Since it is a hover action on drop down list item, it should be linked to List Item BG Color Hovered instead of button focus color.

### ❌ Actual Behavior

List item BG Color Hovered is not linked to,
- drop down menu items on hover (Instead button focus color is linked to this.)

**Comment by mienaiyami** [comment] 2023-08-16 08:04
It is as intended, everything from BG color to focused color is linked to button.
Let me know if there is an issue with that. If not, I will be closing it as not planned.

**Comment by mienaiyami** [comment] 2023-08-17 08:23
> Since it is a hover action on drop down list item, it should be linked to List Item BG Color Hovered instead of button focus color.

You see, select options are focused on mouse over, it's not actually hover, kind of. If you click enter of space while mouse is over an option you will notice that, also when you use arrow keys to move selection.

I will be changing BG color of select option to "context menu". If it fits better.

**Closed** 2023-08-25 14:44 UTC
Labels: bug
